#!/bin/sh

module load prun

make fibo1

# prun -v -1 -np 1 -sge-script $PRUN_ETC/prun-openmpi `pwd`/fibo1 10 1
# prun -v -1 -np 1 -sge-script $PRUN_ETC/prun-openmpi `pwd`/fibo1 10 2
# prun -v -1 -np 1 -sge-script $PRUN_ETC/prun-openmpi `pwd`/fibo1 10 4
# prun -v -1 -np 1 -sge-script $PRUN_ETC/prun-openmpi `pwd`/fibo1 10 8
# prun -v -1 -np 1 -sge-script $PRUN_ETC/prun-openmpi `pwd`/fibo1 10 16

# prun -v -1 -np 1 -sge-script $PRUN_ETC/prun-openmpi `pwd`/fibo1 20 1
# prun -v -1 -np 1 -sge-script $PRUN_ETC/prun-openmpi `pwd`/fibo1 20 2
# prun -v -1 -np 1 -sge-script $PRUN_ETC/prun-openmpi `pwd`/fibo1 20 4
# prun -v -1 -np 1 -sge-script $PRUN_ETC/prun-openmpi `pwd`/fibo1 20 8
# prun -v -1 -np 1 -sge-script $PRUN_ETC/prun-openmpi `pwd`/fibo1 20 16

prun -v -1 -np 1 -sge-script $PRUN_ETC/prun-openmpi `pwd`/fibo1 25 1
prun -v -1 -np 1 -sge-script $PRUN_ETC/prun-openmpi `pwd`/fibo1 25 2
prun -v -1 -np 1 -sge-script $PRUN_ETC/prun-openmpi `pwd`/fibo1 25 4
prun -v -1 -np 1 -sge-script $PRUN_ETC/prun-openmpi `pwd`/fibo1 25 8
prun -v -1 -np 1 -sge-script $PRUN_ETC/prun-openmpi `pwd`/fibo1 25 16

# prun -v -1 -np 1 -sge-script $PRUN_ETC/prun-openmpi `pwd`/fibo1 35 1
# prun -v -1 -np 1 -sge-script $PRUN_ETC/prun-openmpi `pwd`/fibo1 35 2
# prun -v -1 -np 1 -sge-script $PRUN_ETC/prun-openmpi `pwd`/fibo1 35 4
# prun -v -1 -np 1 -sge-script $PRUN_ETC/prun-openmpi `pwd`/fibo1 35 8
# prun -v -1 -np 1 -sge-script $PRUN_ETC/prun-openmpi `pwd`/fibo1 35 16
