#!/bin/sh
module load prun
make

THREADS=8

cd ../
make pat1_$1x$2.pgm > /dev/null
cd acc/

#prun -v -1 -np 1 -sge-script $PRUN_ETC/prun-openmpi ./example 99999999999 1024
#prun -v -1 -np 1 ./example_seq 12000000 80
#prun -v -1 -np 1 ./matmul_seq $1

#prun -v -1 -np 1 -sge-script $PRUN_ETC/prun-openmpi ./matmul_omp 100 $THREADS 10
#prun -v -1 -np 1 -sge-script $PRUN_ETC/prun-openmpi ./matmul_omp 1000 $THREADS 10
#prun -v -1 -np 1 -sge-script $PRUN_ETC/prun-openmpi ./matmul_omp 2500 $THREADS 10
#prun -v -1 -np 1 -sge-script $PRUN_ETC/prun-openmpi ./matmul_omp 5000 $THREADS 10

#prun -v -1 -np 1 -native '-l gpu=GTX480' ./matmul_acc 100 $THREADS 10
#prun -v -1 -np 1 -native '-l gpu=GTX480' ./matmul_acc 1000 $THREADS 10
#prun -v -1 -np 1 -native '-l gpu=GTX480' ./matmul_acc 2500 $THREADS 10
#prun -v -1 -np 1 -native '-l gpu=GTX480' ./matmul_acc 5000 $THREADS 10

prun -v -1 -np 1 -native '-l gpu=GTX480' ./heat_acc -n $2 -m $1 -i 5000 -k 1000 -e 0 -c ../pat1_$1x$2.pgm -t ../pat1_$1x$2.pgm -L -1.000000e+02 -H 1.000000e+02 -p 1 
#prun -v -1 -np 1 -native '-l gpu=GTX480' ./matmul_acc 100 $THREADS 10 
