#!/bin/sh
module load prun
make -j

THREADS=8

#cd ../
#make pat1_$1x$2.pgm > /dev/null
#cd acc/

#prun -v -1 -np 1 -sge-script $PRUN_ETC/prun-openmpi ./example 99999999999 1024
#prun -v -1 -np 1 ./example_seq 12000000 80
#prun -v -1 -np 1 ./matmul_seq $1

#prun -v -1 -np 1 -sge-script $PRUN_ETC/prun-openmpi ./matmul_omp 100 $THREADS 10
#prun -v -1 -np 1 -sge-script $PRUN_ETC/prun-openmpi ./matmul_omp 1000 $THREADS 10
#prun -v -1 -np 1 -sge-script $PRUN_ETC/prun-openmpi ./matmul_omp 2500 $THREADS 10
#prun -v -1 -np 1 -sge-script $PRUN_ETC/prun-openmpi ./matmul_omp 5000 $THREADS 10

#prun -v -1 -np 1 -native '-l gpu=GTX480' ./matmul_acc 100 $THREADS 10
#prun -v -1 -np 1 -native '-l gpu=GTX480' ./matmul_acc 1000 $THREADS 10
#prun -v -1 -np 1 -native '-l gpu=GTX480' ./matmul_acc 2500 $THREADS 10
#prun -v -1 -np 1 -native '-l gpu=GTX480' ./matmul_acc 5000 $THREADS 10

#prun -v -1 -np 1 ./example_chpl --n=$1 --verbose=$2
prun -v -1 -np 1 ./heat --Gc=/home/mwr750/PCS2/heat-1.14/cpl/pattern1_100x150.pgm --Gt=/home/mwr750/PCS2/heat-1.14/cpl/pattern1_100x150.pgm --Gi=50 --Gk=10
#prun -v -1 -np 1 -native '-l gpu=GTX480' ./matmul_acc 100 $THREADS 10 
